name: ISeeYou
version: ${version}
main: cn.xor7.iseeyou.ISeeYou
api-version: '1.20'
dependencies:
  server:
    Themis:
      load: BEFORE
      required: false
    Matrix:
      load: BEFORE
      required: false
    Vulcan:
      load: BEFORE
      required: false