name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
      
      - name: Execute Gradle build
        run: ./gradlew shadowJar

      - uses: actions/upload-artifact@v4
        with:
          name: Package JAR
          path: build/libs

      - name: publish release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: build/libs/ISeeYou-*-all.jar
          prerelease: false
